// Generated by https://quicktype.io

export interface RespuestaPosts {
    mensaje: string;
    pagina:  number;
    posts:   Post[];
}

export interface Post {
    imgs?:    string[];
    _id?:     string;
    mensaje?: string;
    coords?:  string;
    user?:    User;
    created?: string;
}



export interface User {
    avatar?: string;
    _id?:    string;
    nombre?: string;
    email?:  string;
}

